name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      
      - name: ruff-check
        run: ruff check --fix
      
      - name: ruff-format 
        run: ruff format
